name: Static test
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
      
    - 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - 
      run: dotnet tool install --global dotnet-format

    - 
      run: |
        echo "-------------------------"
        dotnet format --severity warn --verbosity normal --verify-no-changes
        continue-on-error: true
        
    - 
      run: |
        echo "-------------------------"
        cat Class1.cs


