name: Static test
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
      
    - 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    -
      run: |
        ls
        
    -
      run: |
        dotnet user-secrets set "AAA" "1"
        dotnet user-secrets set "BBB" "1"
        dotnet user-secrets set "CCC" "1"

    -
      run: |
        dotnet user-secrets remove "AAA" 
        dotnet user-secrets remove "BBB" 
        dotnet user-secrets remove "CCC" 

